env:
  DOMAIN: &DOMAIN 169.48.201.211.nip.io
  ENABLE_OPI_STAGING: true
  UAA_HOST: uaa.169.48.201.211.nip.io
  UAA_PORT: 2793

kube:
  auth: rbac
  external_ips: &external_ips
  - 169.48.201.211
  storage_class:
    persistent: hostpath
    shared: hostpath

secrets: &secrets
  BLOBSTORE_PASSWORD: &BLOBSTORE_PASSWORD bits
  CLUSTER_ADMIN_PASSWORD: kobe
  NATS_PASSWORD: &NATS_PASSWORD deeeznatz
  UAA_ADMIN_CLIENT_SECRET: wuaau

services: &services
  loadbalanced: false

eirini:
  env:
    DOMAIN: *DOMAIN
  services: *services
  opi:
    use_registry_ingress: true
    #Enable if use_registry_ingress is set to 'true'
    ingress_endpoint: nk-eirini-old.us-south.containers.appdomain.cloud
    #Enable if your cluster is using docker,
    #by default eirini will assume containerd
    use_docker: false
    image_tag: latest

    namespace: eirini
    init_image: nimak/opi-init
    image: nimak/opi
    image_tag: latest
    rootfs_version: 24.0.0
    rootfs_tag: v24.0.0
    rootfs_patcher_timeout: -1ns
    stager:
      downloader_image: eirini/recipe-downloader
      downloader_image_tag: latest
      executor_image: eirini/recipe-executor
      executor_image_tag: latest
      uploader_image: eirini/recipe-uploader
      uploader_image_tag: latest

  kube:
    external_ips: *external_ips

  secrets:
    BITS_SERVICE_SECRET: bits
    BITS_SERVICE_SIGNING_USER_PASSWORD: bits
    NATS_PASSWORD: *NATS_PASSWORD
    BLOBSTORE_PASSWORD: *BLOBSTORE_PASSWORD
    BITS_TLS_KEY: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAw2MCcpTSo1EELWeNRTyafmyh2vIcZj83TYK0n3Do/tGie+zs
      6Zq1KdIwK838WrqoaPBZTuv6Smlgc/I7wlp/hX4UDK6tDUX+75a6aQjQdFyaZJPc
      s0n3gNzDtOrVlHSx3ywnyMtasX4+HLqx6i3/eeT46DK8kftCD6wavw/gYfp0/bFU
      qTV85focJqfmZtJbHzi15bvOEYMY09j5wV62/528i4FPIb4pDoGQ1D1WkG6o2osY
      fpZEd0iPiVkmV1Qo/Dn92vVC2G4jLG59oKR9unkMFWCcHnjoHhnDwGb98yieZV99
      D/b4fgXNsse8N1FWfbZZz4KDtWwI07BwMMroqwIDAQABAoIBAQC495AnnM/ToCzO
      Nwu8EeVH7dtEBJPyD8Jw9F292wwXv6mMm/ykIbuDfeHwdi6CTdaEkZRabHcj3qJa
      4WTFVxsF6xdb8jkNKchwVEbgjGGa5teag4gZitpt+ZCkQvQyeE6zMX/wTOLsyNBQ
      LkWjpiwG30bruqxdnnkpkQo4+fS3itVjnitBMnYTPENTgWMCGr4ObB1cH9I33A4Y
      UaHo0Ht2+09p39pz/x8TeoiR+mbpXaZTFVJxiAmqzZ1kXTmkBakDhCN5i5MpfZ9t
      ZpNbRJiHeHhc51P9LX/mm0A5s8j4Rk9v0nIpbXDqc1vkZAPI9Tgnn3EMD4qDiuL0
      N9teKhzRAoGBAOemnii3RYGpUymj5jAIhTPBJ+NfePCcSYnhu6KnKIQk2ZikyWNv
      iXOongdoKISIEzkubfEL4vP3T57vnnmtKOB1NjxQ+oTTHlaVurcPQssetBmVox9Y
      AboVgRNk7aORm89xCUWXcH0pTUx5aPOpvUy8pY2ivC9635m7IRExx1MNAoGBANfs
      lBrOquLtJ5fCXz//OcSfLVGtdr0cCgpzZAetwY6ZekdqPbuzSem7k2vs/T1MnG8Z
      kWJGwyVgkyDWF++HhRL/O2HA+lXBLRGoXM7WZ9BIupMYP0dUhHp1lQV4KvfhGFFT
      lD4KUK62Fyz9/F825f0kEnyOnRbK9gnw2IXQ0ZyXAoGBALuaGU4aFoVKbtozLRFL
      ZSyjyjz+rcAWoguzLzUrsMlL2pkfIyWPR77OGKUg+mdSmFbfvhPPr44qhGXP4wTh
      clBNPI4eerQlEdXHTr4/8rTy+aIaqE+TA1sDXVQqkbW9D3UxMvQUD/qc/0fmr1Nd
      7Lt/r4eD+mltVjZ28PGu4aDlAoGBAKmBV2MUCqLKeeJw/EVJHxhzvSf5fNVIRbme
      jFBa3zAK3CtkA8JuJQAP+NMo4ERW+Bdfgvobgua8wcNtTq0DPjyDkSJUVDEtzSun
      d/QH7Mdd0NnYlxRwDO/1jl8UzuZ5FpYBfsaVYnFFETyIxq4YcsQepUSS0E8sVanI
      ILIsE+FRAoGAAiBAP4FSgdyLgwdYx2JVdoRNyLOJV+EgEBrUp6pikKOdjJphi+mp
      tWU80aYkjbfpdNqkvfuYDE027dNHk+yfGg3qsPQNHoq55wRMfz9Oj2hLHNm1ZMzh
      bsJhSBVQkLP4JQZHrUEe1Hrtl5qBsd+o18pdNCkYcxqqQgslXIAM97U=
      -----END RSA PRIVATE KEY-----
    BITS_TLS_CRT: |
      -----BEGIN CERTIFICATE-----
      MIIFzzCCBLegAwIBAgISA9v2qAgcyFbbo5usxFqX1mMtMA0GCSqGSIb3DQEBCwUA
      MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
      ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTAyMjgxOTUyMzVaFw0x
      OTA1MjkxOTUyMzVaMDwxOjA4BgNVBAMTMW5rLWVpcmluaS1vbGQudXMtc291dGgu
      Y29udGFpbmVycy5hcHBkb21haW4uY2xvdWQwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQDDYwJylNKjUQQtZ41FPJp+bKHa8hxmPzdNgrSfcOj+0aJ77Ozp
      mrUp0jArzfxauqho8FlO6/pKaWBz8jvCWn+FfhQMrq0NRf7vlrppCNB0XJpkk9yz
      SfeA3MO06tWUdLHfLCfIy1qxfj4curHqLf955PjoMryR+0IPrBq/D+Bh+nT9sVSp
      NXzl+hwmp+Zm0lsfOLXlu84RgxjT2PnBXrb/nbyLgU8hvikOgZDUPVaQbqjaixh+
      lkR3SI+JWSZXVCj8Of3a9ULYbiMsbn2gpH26eQwVYJweeOgeGcPAZv3zKJ5lX30P
      9vh+Bc2yx7w3UVZ9tlnPgoO1bAjTsHAwyuirAgMBAAGjggK7MIICtzAOBgNVHQ8B
      Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB
      /wQCMAAwHQYDVR0OBBYEFC/fxl6WRNKQrHzOaYULqcBDbYxBMB8GA1UdIwQYMBaA
      FKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMwYTAuBggrBgEFBQcw
      AYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcw
      AoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8wcQYDVR0RBGow
      aIIzKi5uay1laXJpbmktb2xkLnVzLXNvdXRoLmNvbnRhaW5lcnMuYXBwZG9tYWlu
      LmNsb3VkgjFuay1laXJpbmktb2xkLnVzLXNvdXRoLmNvbnRhaW5lcnMuYXBwZG9t
      YWluLmNsb3VkMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgw
      JgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYB
      BAHWeQIEAgSB9QSB8gDwAHYAdH7agzGtMxCRIZzOJU9CcMK//V5CIAjGNzV55hB7
      zFYAAAFpNeFbIgAABAMARzBFAiEA0A/sH5jbsS40xDlLYP3SVbVX64Z8A7xIuzFq
      F7uGHd4CIDoiBemYPNWR+8dbp3kvXd4/0Mrxru4ZygxEXmXOR0ctAHYAKTxRllTI
      OWW6qlD8WAfUt2+/WHopctykwwz05UVH9HgAAAFpNeFbfgAABAMARzBFAiEAqbfc
      pb2tovizLnWWXzUKDgOv+wqUwxxWwl+jnLjh8IACIFKZxmzoxa8uCi4SgXSX48JS
      SwNGakWOml8ggy1hXyGsMA0GCSqGSIb3DQEBCwUAA4IBAQAZB2GcgJOltKrymIKe
      eFucpgFfJ5ap1MuakOEBpi5WdGDKhp/4k4YBphcAu22HgJSz6BwRLlaF+a2tK4k8
      6aNrcA83gUM+EbjRIk5dw1MiemtN1p0OknFNpGi2poaVsOGLd44zXYD7fiD69q5X
      /d2ncEAHs5wVSY3zDV6nwPkvXLt8XFFIn0zRPVhdZLZfePBlDL75uC3wi7vWlZ9B
      78rtXFpfFZtTEBG8nmr7hvXPeIzP01SWsDkonMbnJvEc8cQAnVyMfkj6PqxXCS/f
      lxo0AUPD/l6Mr4sGZqZ+VN2UnH9d7SKPDE/zALqSjoAy4dQpRCLK1lwjfYsqGofj
      USNf
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
      SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
      GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
      q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
      SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
      Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
      a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
      /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
      CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
      bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
      c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
      VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
      ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
      MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
      Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
      AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
      uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
      wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
      X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
      PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
      KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
      -----END CERTIFICATE-----

